-------------------------------------------------------------------------------
Test set: EndangeredAnimalsTest
-------------------------------------------------------------------------------
Tests run: 7, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 0.845 sec <<< FAILURE! - in EndangeredAnimalsTest
findByIdReturnsCorrectInfo(EndangeredAnimalsTest)  Time elapsed: 0.424 sec  <<< ERROR!
org.sql2o.Sql2oException: 
Error in executeUpdate, ERROR: relation "sightings" does not exist
  Position: 13
Caused by: org.postgresql.util.PSQLException: 
ERROR: relation "sightings" does not exist
  Position: 13

deleteAllEntries(EndangeredAnimalsTest)  Time elapsed: 0.116 sec  <<< ERROR!
org.sql2o.Sql2oException: 
Error in executeUpdate, ERROR: relation "sightings" does not exist
  Position: 13
Caused by: org.postgresql.util.PSQLException: 
ERROR: relation "sightings" does not exist
  Position: 13

ensureNameFieldCannotBeEmpty(EndangeredAnimalsTest)  Time elapsed: 0.009 sec  <<< ERROR!
org.sql2o.Sql2oException: 
Error in executeUpdate, ERROR: relation "sightings" does not exist
  Position: 13
Caused by: org.postgresql.util.PSQLException: 
ERROR: relation "sightings" does not exist
  Position: 13

testInstanceOfEndangeredAnimalsClass_true(EndangeredAnimalsTest)  Time elapsed: 0.023 sec  <<< ERROR!
org.sql2o.Sql2oException: 
Error in executeUpdate, ERROR: relation "sightings" does not exist
  Position: 13
Caused by: org.postgresql.util.PSQLException: 
ERROR: relation "sightings" does not exist
  Position: 13

allInstancesAreSaved(EndangeredAnimalsTest)  Time elapsed: 0.06 sec  <<< ERROR!
org.sql2o.Sql2oException: 
Error in executeUpdate, ERROR: relation "sightings" does not exist
  Position: 13
Caused by: org.postgresql.util.PSQLException: 
ERROR: relation "sightings" does not exist
  Position: 13

deleteByID(EndangeredAnimalsTest)  Time elapsed: 0.076 sec  <<< ERROR!
org.sql2o.Sql2oException: 
Error in executeUpdate, ERROR: relation "sightings" does not exist
  Position: 13
Caused by: org.postgresql.util.PSQLException: 
ERROR: relation "sightings" does not exist
  Position: 13

ensureEntryIsUpdatedCorrectly(EndangeredAnimalsTest)  Time elapsed: 0.062 sec  <<< ERROR!
org.sql2o.Sql2oException: 
Error in executeUpdate, ERROR: relation "sightings" does not exist
  Position: 13
Caused by: org.postgresql.util.PSQLException: 
ERROR: relation "sightings" does not exist
  Position: 13

